version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: shopflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shopflow
      POSTGRES_PASSWORD: shopflow_dev_pw
      POSTGRES_DB: shopflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: